### ISSUE TITLE
Will not open on Windows 10

### ISSUE THREAD

**Issue by quinnjalan** [phrack/ShootOFF#385] opened 2016-02-22 23:36 UTC
I downloaded and installed ShootOFF and Java 8. When I double click on ShootOFF.jar a window pops up and closes in a nano second. I tested on my work laptop (Win 8) and it opened without issue. However, I can't really leave it on there! Can ideas? I'll be happy to supply log files etc. Thanks, Alan

**Comment by phrack** [comment] 2016-02-23 12:47
@cbdmaul certainly knows more about Windows 10 than me and may have ideas. 

For starters, I suggest running ShootOFF-diagnostics.jar in the same directory that contains ShootOFF.jar. Wait about 15 seconds and a file called shootoff-diagnostics.log will appear. Please attach it to this thread by dragging and dropping it onto the comment field when you reply.

**Comment by quinnjalan** [comment] 2016-02-23 13:53
Thanks for getting back to me. I get the same results where a window pops
up and closes in a nano second and I do not get the expected
shootoff-diagnostics.log file in the shootoff folder. I tested on my Win 8
(work) laptop and I get a log (its blank) but at least it producing
something. Any more ideas? Cheers, Alan

**Comment by phrack** [comment] 2016-02-23 14:08
Huh, I am not surprised that you get the same flash, but the fact that you don't get a log even is disturbing.

Do you know how to use the command line?

**Comment by cbdmaul** [comment] 2016-02-23 14:11
I've used W10 for literally 30 seconds total but I have access to a W10 laptop.  I'll try to reproduce tonight.

**Comment by quinnjalan** [comment] 2016-02-23 15:48
phrack, yes on command line. What do you want me to do?

cbdmaul, thank on testing later

Cheers, Alan

**Comment by phrack** [comment] 2016-02-23 16:03
cd to the directory containing ShootOFF.jar. Run:

java -version

Then run:

java -jar ShootOFF.jar

Copy and paste any output here.

**Comment by quinnjalan** [comment] 2016-02-23 17:20
It opened via the Command Line. See attached image for my steps. Progress
is good!

**Comment by phrack** [comment] 2016-02-23 18:13
I don't think GitHub includes attachments from email replies. Can you reply on the website and drag and drop the images onto the comment box?

**Comment by quinnjalan** [comment] 2016-02-23 18:23
![shoootoff_image_1](https://cloud.githubusercontent.com/assets/17418519/13261963/8409b9ee-da30-11e5-8e54-cea9f2f125e6.png)

Try the above.

**Comment by phrack** [comment] 2016-02-23 18:38
OK, so it looks like it opens fine from the command line (although the shot timer on the right is smooshed). The question then is: why does it not open right when double clicked?

Two thoughts come to my mind:
1. Are there multiple versions of Java installed? If yes, an older version may be getting used, in which case it would fail when it realizes ShootOFF requires minimum Java 8.
2. The .jar extension may be associated with something else. You could try right clicking the .jar and looking at the Open With menu to see if it's associated with something other than Java.

**Comment by quinnjalan** [comment] 2016-02-23 19:30
See this video for what I'm doing and seeing: http://screencast.com/t/wqEz1p1tL1m
[ShootOff_Command_line_text.txt](https://github.com/phrack/ShootOFF/files/143273/ShootOff_Command_line_text.txt)

Also, I only have one version of Java installed Jave 8 Update 73

**Comment by cbdmaul** [comment] 2016-02-23 19:33
That error is irrelevant, it is failing to clean up a dll on closing ShootOFF.

Can you address phrack's 2nd idea?

**Comment by quinnjalan** [comment] 2016-02-23 20:50
#2 The .jar extension may be associated with something else. You could try right clicking the .jar and looking at the Open With menu to see if it's associated with something other than Java.

Made no difference. I changed the association away from and back to Java.

**Comment by phrack** [comment] 2016-02-24 00:00
There appears to be a solution linked to from here:

http://answers.microsoft.com/en-us/windows/forum/games_windows_10/cant-open-jar-file-using-windows-10/98f81ae5-0cbb-47f7-b7ff-49275e19e7a2?auth=1&rtAction=1441586909922

**Comment by quinnjalan** [comment] 2016-02-24 01:25
I ran the exe in the link and it asked if I wanted to associate jar file to
Java, I choose yes. The ShootOFF window popped up for a 1/2 nano second
longer than before and once again it close.

**Comment by cbdmaul** [comment] 2016-02-24 03:17
Was not able to reproduce.  Windows 10, java 8u73 x64, shootoff 3.6.  Ran just fine.

I suggest uninstalling java and reinstalling.  Make sure it is 8u73 x64.

**Comment by quinnjalan** [comment] 2016-02-24 14:22
Will test later on tonight when I get home. Thanks

**Comment by phrack** [comment] 2016-02-27 18:47
I am planning to close this tomorrow unless there is some compelling update.

**Closed as completed** 2016-02-28 15:16 UTC
